ELab/config/routes.rb
Rails.application.routes.draw do
  resources :chats
  get 'top/index'

  root to: "top#index"

  resources :companies
  resources :lessons
  resources :people
  resources :labs
  resources :colleges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ELab/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ELab/app/models/big_category.rb
class BigCategory < ApplicationRecord
end

ELab/app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :lab
end

ELab/app/models/college.rb
class College < ApplicationRecord
  has_many :labs
end

ELab/app/models/company.rb
class Company < ApplicationRecord
  has_many :company_labs, dependent: :destroy
  has_many :labs, :through => :company_labs

  accepts_nested_attributes_for :company_labs, allow_destroy: true
 
end

ELab/app/models/company_lab.rb
class CompanyLab < ApplicationRecord
  belongs_to :company
  belongs_to :lab

  validates :company_id,
    uniqueness: {
      message: "同じ組み合わせのレコードが既に存在します。",
      scope: [:lab_id]
    }
end

ELab/app/models/lab.rb
class Lab < ApplicationRecord
  has_many :people
  belongs_to :college
  has_many :lesson_labs, dependent: :destroy
  has_many :lessons, :through => :lesson_labs
  has_many :company_labs, dependent: :destroy
  has_many :companies, :through => :company_labs
  has_many :small_category_labs, dependent: :destroy
  has_many :labs, :through => :small_category_labs

  accepts_nested_attributes_for :small_category_labs, allow_destroy: true
  accepts_nested_attributes_for :lesson_labs, allow_destroy: true
  accepts_nested_attributes_for :people, allow_destroy: true

  def self.search(search)
    if search
      Lab.where(['name LIKE ?', "%#{search}%"])
    else
      Lab.all #全て表示。
    end
  end

end

ELab/app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :lesson_labs, dependent: :destroy
  has_many :labs, :through => :lesson_labs

  accepts_nested_attributes_for :lesson_labs, allow_destroy: true
end

ELab/app/models/lesson_lab.rb
class LessonLab < ApplicationRecord
  belongs_to :lesson
  belongs_to :lab

  validates :lesson_id,
    uniqueness: {
      message: "同じ組み合わせのレコードが既に存在します。",
      scope: [:lab_id]
    }

end

ELab/app/models/people_lab.rb
class PeopleLab < ApplicationRecord
  belongs_to :person
  belongs_to :lab

  validates :people_id,
    uniqueness: {
      message: "同じ組み合わせのレコードが既に存在します。",
      scope: [:labs_id]
    }
end

ELab/app/models/person.rb
class Person < ApplicationRecord
  belongs_to :lab

  validates :name, uniqueness: true
end

ELab/app/models/small_category.rb
class SmallCategory < ApplicationRecord
  has_many :small_category_labs, dependent: :destroy
  has_many :labs, :through => :small_category_labs

  accepts_nested_attributes_for :small_category_labs, allow_destroy: true
 
end

ELab/app/models/small_category_lab.rb
class SmallCategoryLab < ApplicationRecord
  belongs_to :small_category
  belongs_to :lab

  validates :small_category_id,
    uniqueness: {
      message: "同じ組み合わせのレコードが既に存在します。",
      scope: [:lab_id]
    }
end

ELab/app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.fetch(:lesson, {})
    end
end

ELab/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

ELab/app/helpers/application_helper.rb
module ApplicationHelper
end

ELab/app/helpers/chats_helper.rb
module ChatsHelper
end

ELab/app/helpers/colleges_helper.rb
module CollegesHelper
end

ELab/app/helpers/companies_helper.rb
module CompaniesHelper
end

ELab/app/helpers/labs_helper.rb
module LabsHelper
end

ELab/app/helpers/lessons_helper.rb
module LessonsHelper
end

ELab/app/helpers/people_helper.rb
module PeopleHelper
end

ELab/app/helpers/top_helper.rb
module TopHelper
end

ELab/app/views/lessons/_form.html.erb
<%= form_for(lesson) do |f| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ELab/app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

ELab/app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lessons</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

ELab/app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

ELab/app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>