ELab/config/routes.rb
Rails.application.routes.draw do
  resources :chats
  get 'top/index'

  root to: "top#index"

  resources :companies
  resources :lessons
  resources :people
  resources :labs
  resources :colleges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ELab/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ELab/app/models/big_category.rb
class BigCategory < ApplicationRecord
end

ELab/app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :lab
end

ELab/app/models/college.rb
class College < ApplicationRecord
  has_many :labs
end

ELab/app/models/company.rb
class Company < ApplicationRecord
  has_many :company_labs, dependent: :destroy
  has_many :labs, :through => :company_labs

  accepts_nested_attributes_for :company_labs, allow_destroy: true
 
end

ELab/app/models/company_lab.rb
class CompanyLab < ApplicationRecord
  belongs_to :company
  belongs_to :lab

  validates :company_id,
    uniqueness: {
      message: "同じ組み合わせのレコードが既に存在します。",
      scope: [:lab_id]
    }
end

ELab/app/models/lab.rb
class Lab < ApplicationRecord
  has_many :people
  belongs_to :college
  has_many :lesson_labs, dependent: :destroy
  has_many :lessons, :through => :lesson_labs
  has_many :company_labs, dependent: :destroy
  has_many :companies, :through => :company_labs
  has_many :small_category_labs, dependent: :destroy
  has_many :labs, :through => :small_category_labs

  accepts_nested_attributes_for :small_category_labs, allow_destroy: true
  accepts_nested_attributes_for :lesson_labs, allow_destroy: true
  accepts_nested_attributes_for :people, allow_destroy: true

  def self.search(search)
    if search
      Lab.where(['name LIKE ?', "%#{search}%"])
    else
      Lab.all #全て表示。
    end
  end

end

ELab/app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :lesson_labs, dependent: :destroy
  has_many :labs, :through => :lesson_labs

  accepts_nested_attributes_for :lesson_labs, allow_destroy: true
end

ELab/app/models/lesson_lab.rb
class LessonLab < ApplicationRecord
  belongs_to :lesson
  belongs_to :lab

  validates :lesson_id,
    uniqueness: {
      message: "同じ組み合わせのレコードが既に存在します。",
      scope: [:lab_id]
    }

end

ELab/app/models/people_lab.rb
class PeopleLab < ApplicationRecord
  belongs_to :person
  belongs_to :lab

  validates :people_id,
    uniqueness: {
      message: "同じ組み合わせのレコードが既に存在します。",
      scope: [:labs_id]
    }
end

ELab/app/models/person.rb
class Person < ApplicationRecord
  belongs_to :lab

  validates :name, uniqueness: true
end

ELab/app/models/small_category.rb
class SmallCategory < ApplicationRecord
  has_many :small_category_labs, dependent: :destroy
  has_many :labs, :through => :small_category_labs

  accepts_nested_attributes_for :small_category_labs, allow_destroy: true
 
end

ELab/app/models/small_category_lab.rb
class SmallCategoryLab < ApplicationRecord
  belongs_to :small_category
  belongs_to :lab

  validates :small_category_id,
    uniqueness: {
      message: "同じ組み合わせのレコードが既に存在します。",
      scope: [:lab_id]
    }
end

ELab/app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.fetch(:college, {})
    end
end

ELab/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

ELab/app/helpers/application_helper.rb
module ApplicationHelper
end

ELab/app/helpers/chats_helper.rb
module ChatsHelper
end

ELab/app/helpers/colleges_helper.rb
module CollegesHelper
end

ELab/app/helpers/companies_helper.rb
module CompaniesHelper
end

ELab/app/helpers/labs_helper.rb
module LabsHelper
end

ELab/app/helpers/lessons_helper.rb
module LessonsHelper
end

ELab/app/helpers/people_helper.rb
module PeopleHelper
end

ELab/app/helpers/top_helper.rb
module TopHelper
end

ELab/app/views/colleges/_form.html.erb
<%= form_for(college) do |f| %>
  <% if college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
      <% college.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ELab/app/views/colleges/edit.html.erb
<h1>Editing College</h1>

<%= render 'form', college: @college %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>

ELab/app/views/colleges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colleges</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
	<td><%= college.name  %></td>
        <td><%= link_to 'Show', college %></td>
        <td><%= link_to 'Edit', edit_college_path(college) %></td>
        <td><%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College', new_college_path %>

ELab/app/views/colleges/new.html.erb
<h1>New College</h1>

<%= render 'form', college: @college %>

<%= link_to 'Back', colleges_path %>

ELab/app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>